# PanGBank Tutorial: Analyzing AMR Genes in Pangenomes

This tutorial demonstrates how to:
1. Retrieve pangenomes from PanGBank
2. Annotate gene families with AMRFinderPlus
3. Cluster Regions of Genomic Plasticity (RGPs)
4. Analyze the distribution of AMR genes across the pangenome

## Step 1: Download Pangenome from PanGBank

Search for *Escherichia coli* F pangenomes in the GTDB_refseq collection.

In [1]:
! pangbank search-pangenomes --collection GTDB_refseq --taxon "s__Escherichia coli_F"

[12:01:45] INFO     Counting pangenomes for                    ]8;id=11504;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py\pangenomes.py]8;;\:]8;id=999806;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py#103\103]8;;\
                    taxon_name=s__Escherichia coli_F &
                    substring_taxon_match=True &
                    only_latest_release=True &
                    collection_name=GTDB_refseq
           INFO     Found 1 pangenome matching search          ]8;id=120053;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py\pangenomes.py]8;;\:]8;id=710968;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py#112\112]8;;\
                    criteria.
           INFO     Fetching information for the 1 pangenome.  ]8;id=747525;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py\pangenomes.py]8;;\:]8;id=976126;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py#114\114]8;;\
Fetching pangenome ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--           INFO     Found 1 pangenome matching search          ]8;id=120053;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py\pangenomes.py]8;;\:]8;id=710968;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py#112\112]8;;\
                    criteria.
           INFO     Fetching information for the 1 pangenome.  ]8;id=747525;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py\pangenomes.py]8;;\:]8;id=976126;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py#114\114]8;;\
Fetching pangenome ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[12:01:46] INFO     The 1 pangenome matching search criteria   ]8;id=513427;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py\pangenomes.py]8;;\:]8;id=93838;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py#152\152]8;;\
                    is from 1 collection : 'GTDB_refseq'
           INFO     Saving pangenomes information to                 ]8;id=324019;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/main.py\main.py]8;;\:]8;id=400582;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/main.py#240\240]8;;\
                    'pangbank/pangenomes.tsv'
Fetching pangenome ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[12:01:46] INFO     The 1 pangenome matching search criteria   ]8;id=513427;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py\pangenomes.py]8;;\:]8;id=93838;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/pangenomes.py#152\152]8;;\
                    is from 1 collection : 'GTDB_refseq'
           INFO     Saving pangenomes information to                 ]8;id=324019;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/main.py\main.py]8;;\:]8;id=400582;file:///home/jmainguy/miniconda3/envs/ppanggo_dev/lib/python3.12/site-packages/pangbank_cli/main.py#240\240]8;;\
                    'pangbank/pangenomes.tsv'

In [2]:
! ppanggolin info -p "pangbank/pangenomes/GTDB_refseq_s__Escherichia_coli_F_id616.h5" --content

Content:
    Genes: 610065
    Genomes: 125
    Families: 16193
    Edges: 24412
    Persistent:
        Family_count: 3670
        min_genomes_frequency: 0.9
        max_genomes_frequency: 1.0
        sd_genomes_frequency: 0.02
        mean_genomes_frequency: 0.99
    Shell:
        Family_count: 3114
        min_genomes_frequency: 0.07
        max_genomes_frequency: 0.97
        sd_genomes_frequency: 0.24
        mean_genomes_frequency: 0.29
    Cloud:
        Family_count: 9409
        min_genomes_frequency: 0.01
        max_genomes_frequency: 0.07
        sd_genomes_frequency: 0.02
        mean_genomes_frequency: 0.02
    Number_of_partitions: 7
    Shell_S5: 1942
    Shell_S2: 264
    Shell_S1: 350
    Shell_S4: 332
    Shell_S3: 226
    Genomes_fluidity:
        all: 0.145
        shell: 0.524
        cloud: 0.333
        accessory: 0.602
    RGP: 8470
    Spots: 193
    Modules:
        Number_of_modules: 578
        Families_in_Modules: 3798
        Partition_composition:
            Persistent: 0.0
            Shell: 33.46
            Cloud: 66.54

## Step 2: Extract Gene Family Sequences

Export protein sequences for all gene families from the pangenome file.

In [3]:
! ppanggolin fasta -p "pangbank/pangenomes/GTDB_refseq_s__Escherichia_coli_F_id616.h5" -f --compress --prot_families all -o families_faa_output

2025-11-18 12:01:49 utils.py:l239 INFO	Command: /home/jmainguy/miniconda3/envs/ppanggo_dev/bin/ppanggolin fasta -p pangbank/pangenomes/GTDB_refseq_s__Escherichia_coli_F_id616.h5 -f --compress --prot_families all -o families_faa_output
2025-11-18 12:01:49 utils.py:l242 INFO	PPanGGOLiN version: 2.2.5
2025-11-18 12:01:49 utils.py:l977 INFO	4 parameters have a non-default value.
2025-11-18 12:01:49 readBinaries.py:l123 INFO	Getting the current pangenome status
2025-11-18 12:01:49 writeSequences.py:l484 INFO	Writing the representative protein sequences of the gene families by reading the pangenome file directly.
  0%|                                             | 0/16193 [00:00<?, ?family/s]2025-11-18 12:01:49 readBinaries.py:l123 INFO	Getting the current pangenome status
2025-11-18 12:01:49 writeSequences.py:l484 INFO	Writing the representative protein sequences of the gene families by reading the pangenome file directly.
100%|██████████████████████████████| 16193/16193 [00:00<00:00, 46923.87family/s]
2025-11-18 12:01:49 readBinaries.py:l747 INFO	Done writing the representative amino acid sequences of the gene families:'families_faa_output/all_protein_families.faa.gz'
100%|██████████████████████████████| 16193/16193 [00:00<00:00, 46923.87family/s]
2025-11-18 12:01:49 readBinaries.py:l747 INFO	Done writing the representative amino acid sequences of the gene families:'families_faa_output/all_protein_families.faa.gz'

## Step 3: Annotate AMR Genes with AMRFinderPlus

Run AMRFinderPlus to identify antimicrobial resistance genes in the gene families.

In [4]:
# need to have amrfinder database downloaded with 'amrfinder -u'
! amrfinder -p "families_faa_output/all_protein_families.faa.gz" --plus --threads 8  -o amrfinder_result.tsv

Running: amrfinder -p families_faa_output/all_protein_families.faa.gz --plus --threads 8 -o amrfinder_result.tsv
Software directory: '/home/jmainguy/miniconda3/envs/ppanggo_dev/bin/'
Software version: 4.0.3
Database directory: '/home/jmainguy/miniconda3/envs/ppanggo_dev/share/amrfinderplus/data/2025-07-16.1'
Database version: 2025-07-16.1
AMRFinder protein-only search
  - include -n NUC_FASTA, --nucleotide NUC_FASTA and -g GFF_FILE, --gff GFF_FILE options to add translated searches
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
Running blastp
Running blastp
Running hmmsearch
Running hmmsearch
Making report
Making report
amrfinder took 16 seconds to complete
amrfinder took 16 seconds to complete

## Step 4: Cluster RGPs

Group similar Regions of Genomic Plasticity (RGPs) into clusters based on gene content similarity.

In [5]:
! ppanggolin rgp_cluster --grr_metric max_grr -p "pangbank/pangenomes/GTDB_refseq_s__Escherichia_coli_F_id616.h5"  -o rgp_cluster -f --add_metadata

2025-11-18 12:02:07 utils.py:l239 INFO	Command: /home/jmainguy/miniconda3/envs/ppanggo_dev/bin/ppanggolin rgp_cluster --grr_metric max_grr -p pangbank/pangenomes/GTDB_refseq_s__Escherichia_coli_F_id616.h5 -o rgp_cluster -f --add_metadata
2025-11-18 12:02:07 utils.py:l242 INFO	PPanGGOLiN version: 2.2.5
2025-11-18 12:02:07 utils.py:l977 INFO	4 parameters have a non-default value.
2025-11-18 12:02:07 readBinaries.py:l123 INFO	Getting the current pangenome status
2025-11-18 12:02:07 readBinaries.py:l1503 INFO	Reading pangenome annotations...
100%|███████████████████████████████████| 125/125 [00:00<00:00, 7199.29genome/s]
100%|███████████████████████████████████| 125/125 [00:00<00:00, 7199.29genome/s]
100%|█████████████████████████████| 18330/18330 [00:00<00:00, 127076.80contig/s]
100%|█████████████████████████████| 18330/18330 [00:00<00:00, 127076.80contig/s]
100%|█████████████████████████████| 610065/610065 [00:04<00:00, 131808.31gene/s]
100%|█████████████████████████████| 610065/610065 [00:04<00:00, 131808.31gene/s]
100%|███████████████████████████████| 12140/12140 [00:00<00:00, 206518.75gene/s]
2025-11-18 12:02:16 readBinaries.py:l1524 INFO	Reading pangenome gene families...
100%|███████████████████████████████| 12140/12140 [00:00<00:00, 206518.75gene/s]
2025-11-18 12:02:16 readBinaries.py:l1524 INFO	Reading pangenome gene families...
100%|██████████████████████| 610065/610065 [00:02<00:00, 272865.55gene family/s]
100%|██████████████████████| 610065/610065 [00:02<00:00, 272865.55gene family/s]
100%|████████████████████████| 16193/16193 [00:00<00:00, 100128.21gene family/s]
2025-11-18 12:02:18 readBinaries.py:l1544 INFO	Reading the RGP...
100%|████████████████████████| 16193/16193 [00:00<00:00, 100128.21gene family/s]
2025-11-18 12:02:18 readBinaries.py:l1544 INFO	Reading the RGP...
100%|███████████████████████████| 119061/119061 [00:00<00:00, 312486.25region/s]
2025-11-18 12:02:19 readBinaries.py:l1554 INFO	Reading the spots...
100%|███████████████████████████| 119061/119061 [00:00<00:00, 312486.25region/s]
2025-11-18 12:02:19 readBinaries.py:l1554 INFO	Reading the spots...
100%|█████████████████████████████████| 4256/4256 [00:00<00:00, 182874.80spot/s]
2025-11-18 12:02:19 readBinaries.py:l1563 INFO	Reading the modules...
100%|███████████████████████████████| 3798/3798 [00:00<00:00, 152912.51module/s]
2025-11-18 12:02:19 rgp_cluster.py:l424 INFO	Dereplicating 8470 RGPs
100%|█████████████████████████████████| 4256/4256 [00:00<00:00, 182874.80spot/s]
2025-11-18 12:02:19 readBinaries.py:l1563 INFO	Reading the modules...
100%|███████████████████████████████| 3798/3798 [00:00<00:00, 152912.51module/s]
2025-11-18 12:02:19 rgp_cluster.py:l424 INFO	Dereplicating 8470 RGPs
100%|██████████████████████████████████| 8470/8470 [00:00<00:00, 250513.04RGP/s]
2025-11-18 12:02:19 rgp_cluster.py:l451 INFO	3977 unique RGPs
100%|██████████████████████████████████| 8470/8470 [00:00<00:00, 250513.04RGP/s]
2025-11-18 12:02:19 rgp_cluster.py:l451 INFO	3977 unique RGPs
2025-11-18 12:02:19 rgp_cluster.py:l691 INFO	Computing GRR metric for 256,439 pairs of RGP.
2025-11-18 12:02:19 rgp_cluster.py:l691 INFO	Computing GRR metric for 256,439 pairs of RGP.
2025-11-18 12:02:27 rgp_cluster.py:l717 INFO	Louvain_communities clustering of RGP  based on max_grr on Graph with 3977 nodes and 3066 edges.
2025-11-18 12:02:27 rgp_cluster.py:l717 INFO	Louvain_communities clustering of RGP  based on max_grr on Graph with 3977 nodes and 3066 edges.
2025-11-18 12:02:27 rgp_cluster.py:l515 INFO	Graph has 2606 clusters using max_grr
2025-11-18 12:02:27 rgp_cluster.py:l515 INFO	Graph has 2606 clusters using max_grr
2025-11-18 12:02:27 rgp_cluster.py:l728 INFO	Add info on identical RGPs merged in the graph
2025-11-18 12:02:27 rgp_cluster.py:l738 INFO	Add RGP information to the graph
2025-11-18 12:02:27 rgp_cluster.py:l728 INFO	Add info on identical RGPs merged in the graph
2025-11-18 12:02:27 rgp_cluster.py:l738 INFO	Add RGP information to the graph
2025-11-18 12:02:27 rgp_cluster.py:l747 INFO	Writing graph in gexf format in rgp_cluster/rgp_cluster.gexf.
2025-11-18 12:02:27 rgp_cluster.py:l747 INFO	Writing graph in gexf format in rgp_cluster/rgp_cluster.gexf.
2025-11-18 12:02:28 rgp_cluster.py:l754 INFO	Writing graph in graphml format in rgp_cluster/rgp_cluster.graphml.
2025-11-18 12:02:28 rgp_cluster.py:l754 INFO	Writing graph in graphml format in rgp_cluster/rgp_cluster.graphml.
2025-11-18 12:02:28 rgp_cluster.py:l760 INFO	Writing rgp clusters in tsv format in rgp_cluster/rgp_cluster.tsv
2025-11-18 12:02:28 rgp_cluster.py:l760 INFO	Writing rgp clusters in tsv format in rgp_cluster/rgp_cluster.tsv

## Step 5: Export Pangenome Data

Generate output files containing information about spots, RGPs, gene families, partitions, and modules.

In [6]:
! ppanggolin write_pangenome  --spots --regions --families_tsv --partitions \
                              --regions_families --output ppanggolin_output \
                                --modules --spot_modules  \
                                -p "pangbank/pangenomes/GTDB_refseq_s__Escherichia_coli_F_id616.h5" -f \

2025-11-18 12:02:30 utils.py:l239 INFO	Command: /home/jmainguy/miniconda3/envs/ppanggo_dev/bin/ppanggolin write_pangenome --spots --regions --families_tsv --partitions --regions_families --output ppanggolin_output --modules --spot_modules -p pangbank/pangenomes/GTDB_refseq_s__Escherichia_coli_F_id616.h5 -f
2025-11-18 12:02:30 utils.py:l242 INFO	PPanGGOLiN version: 2.2.5
2025-11-18 12:02:30 utils.py:l977 INFO	9 parameters have a non-default value.
2025-11-18 12:02:30 readBinaries.py:l123 INFO	Getting the current pangenome status
2025-11-18 12:02:30 utils.py:l977 INFO	9 parameters have a non-default value.
2025-11-18 12:02:30 readBinaries.py:l123 INFO	Getting the current pangenome status
2025-11-18 12:02:30 readBinaries.py:l1503 INFO	Reading pangenome annotations...
100%|███████████████████████████████████| 125/125 [00:00<00:00, 5197.25genome/s]
  0%|                                             | 0/18330 [00:00<?, ?contig/s]2025-11-18 12:02:30 readBinaries.py:l1503 INFO	Reading pangenome annotations...
100%|███████████████████████████████████| 125/125 [00:00<00:00, 5197.25genome/s]
100%|█████████████████████████████| 18330/18330 [00:00<00:00, 127563.23contig/s]
100%|█████████████████████████████| 18330/18330 [00:00<00:00, 127563.23contig/s]
100%|█████████████████████████████| 610065/610065 [00:04<00:00, 131789.95gene/s]
100%|█████████████████████████████| 610065/610065 [00:04<00:00, 131789.95gene/s]
100%|███████████████████████████████| 12140/12140 [00:00<00:00, 201141.03gene/s]
2025-11-18 12:02:39 readBinaries.py:l1524 INFO	Reading pangenome gene families...
100%|███████████████████████████████| 12140/12140 [00:00<00:00, 201141.03gene/s]
2025-11-18 12:02:39 readBinaries.py:l1524 INFO	Reading pangenome gene families...
100%|██████████████████████| 610065/610065 [00:02<00:00, 291557.29gene family/s]
100%|██████████████████████| 610065/610065 [00:02<00:00, 291557.29gene family/s]
100%|████████████████████████| 16193/16193 [00:00<00:00, 109687.64gene family/s]
2025-11-18 12:02:41 readBinaries.py:l1544 INFO	Reading the RGP...
100%|████████████████████████| 16193/16193 [00:00<00:00, 109687.64gene family/s]
2025-11-18 12:02:41 readBinaries.py:l1544 INFO	Reading the RGP...
100%|███████████████████████████| 119061/119061 [00:00<00:00, 323833.64region/s]
2025-11-18 12:02:42 readBinaries.py:l1554 INFO	Reading the spots...
100%|█████████████████████████████████| 4256/4256 [00:00<00:00, 203381.05spot/s]
2025-11-18 12:02:42 readBinaries.py:l1563 INFO	Reading the modules...
100%|███████████████████████████| 119061/119061 [00:00<00:00, 323833.64region/s]
2025-11-18 12:02:42 readBinaries.py:l1554 INFO	Reading the spots...
100%|█████████████████████████████████| 4256/4256 [00:00<00:00, 203381.05spot/s]
2025-11-18 12:02:42 readBinaries.py:l1563 INFO	Reading the modules...
100%|███████████████████████████████| 3798/3798 [00:00<00:00, 150787.70module/s]
2025-11-18 12:02:42 writeFlatPangenome.py:l917 INFO	Writing the list of gene families for each partition ...
100%|███████████████████████████████| 3798/3798 [00:00<00:00, 150787.70module/s]
2025-11-18 12:02:42 writeFlatPangenome.py:l917 INFO	Writing the list of gene families for each partition ...
2025-11-18 12:02:43 writeFlatPangenome.py:l958 INFO	Done writing the list of gene families for each partition
2025-11-18 12:02:43 writeFlatPangenome.py:l973 INFO	Writing the file providing the association between genes and gene families...
  0%|                                             | 0/16193 [00:00<?, ?family/s]2025-11-18 12:02:43 writeFlatPangenome.py:l958 INFO	Done writing the list of gene families for each partition
2025-11-18 12:02:43 writeFlatPangenome.py:l973 INFO	Writing the file providing the association between genes and gene families...
100%|██████████████████████████████| 16193/16193 [00:00<00:00, 26761.92family/s]
100%|██████████████████████████████| 16193/16193 [00:00<00:00, 26761.92family/s]
2025-11-18 12:02:45 writeFlatPangenome.py:l1006 INFO	Done writing the file providing the association between genes and gene families: 'ppanggolin_output/gene_families.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1006 INFO	Done writing the file providing the association between genes and gene families: 'ppanggolin_output/gene_families.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1064 INFO	Done writing spots in 'ppanggolin_output/summarize_spots.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1064 INFO	Done writing spots in 'ppanggolin_output/summarize_spots.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1240 INFO	Writing functional modules...
2025-11-18 12:02:45 writeFlatPangenome.py:l1240 INFO	Writing functional modules...
2025-11-18 12:02:45 writeFlatPangenome.py:l1248 INFO	Done writing functional modules to: 'ppanggolin_output/functional_modules.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1211 INFO	Writing functional modules summary...
2025-11-18 12:02:45 writeFlatPangenome.py:l1248 INFO	Done writing functional modules to: 'ppanggolin_output/functional_modules.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1211 INFO	Writing functional modules summary...
2025-11-18 12:02:45 writeFlatPangenome.py:l1229 INFO	Done writing module summary: 'ppanggolin_output/modules_summary.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1259 INFO	Writing modules to genomes associations...
2025-11-18 12:02:45 writeFlatPangenome.py:l1229 INFO	Done writing module summary: 'ppanggolin_output/modules_summary.tsv'
2025-11-18 12:02:45 writeFlatPangenome.py:l1259 INFO	Writing modules to genomes associations...
2025-11-18 12:02:47 writeFlatPangenome.py:l1270 INFO	Done writing modules to genomes associations to: 'ppanggolin_output/modules_in_genomes.tsv'
2025-11-18 12:02:47 writeFlatPangenome.py:l1281 INFO	Writing modules to spot associations...
2025-11-18 12:02:47 writeFlatPangenome.py:l1270 INFO	Done writing modules to genomes associations to: 'ppanggolin_output/modules_in_genomes.tsv'
2025-11-18 12:02:47 writeFlatPangenome.py:l1281 INFO	Writing modules to spot associations...
2025-11-18 12:02:47 writeFlatPangenome.py:l1299 INFO	Done writing module to spot associations to: ppanggolin_output/modules_spots.tsv
2025-11-18 12:02:47 writeFlatPangenome.py:l1310 INFO	Clustering RGPs based on module content...
2025-11-18 12:02:47 writeFlatPangenome.py:l1299 INFO	Done writing module to spot associations to: ppanggolin_output/modules_spots.tsv
2025-11-18 12:02:47 writeFlatPangenome.py:l1310 INFO	Clustering RGPs based on module content...
2025-11-18 12:02:47 writeFlatPangenome.py:l1347 INFO	RGP and associated modules are listed in : ppanggolin_output/modules_RGP_lists.tsv
2025-11-18 12:02:47 writeFlatPangenome.py:l1347 INFO	RGP and associated modules are listed in : ppanggolin_output/modules_RGP_lists.tsv

In [7]:
! tree

.
├── amrfinder_result.tsv
├── families_faa_output
│   └── all_protein_families.faa.gz
├── pangbank
│   ├── pangenomes
│   │   └── GTDB_refseq_s__Escherichia_coli_F_id616.h5
│   └── pangenomes.tsv
├── pangbank_tutorial.ipynb
│   ├── pangenomes
│   │   └── GTDB_refseq_s__Escherichia_coli_F_id616.h5
│   └── pangenomes.tsv
├── pangbank_tutorial.ipynb
├── ppanggolin_output
│   ├── functional_modules.tsv
│   ├── gene_families.tsv
│   ├── modules_in_genomes.tsv
│   ├── modules_RGP_lists.tsv
│   ├── modules_spots.tsv
│   ├── modules_summary.tsv
│   ├── partitions
│   │   ├── cloud.txt
│   │   ├── exact_accessory.txt
│   │   ├── exact_core.txt
│   │   ├── persistent.txt
│   │   ├── S1.txt
│   │   ├── S2.txt
│   │   ├── S3.txt
│   │   ├── S4.txt
│   │   ├── S5.txt
│   │   ├── shell.txt
│   │   ├── soft_accessory.txt
│   │   └── soft_core.txt
│   ├── regions_of_genomic_plasticity.tsv
│   ├── rgp_families.tsv
│   ├── spots.tsv
│   └── summarize_spots.tsv
└── rgp_cluster
    ├── rgp_cluster.gexf
    ├── rgp_cluster.graphml
    └── rgp_cluster.tsv

7 directories, 30 files
├── ppanggolin_output
│   ├── functional_modules.tsv
│   ├── gene_families.tsv
│   ├── modules_in_genomes.tsv
│   ├── modules_RGP_lists.tsv
│   ├── modules_spots.tsv
│   ├── modules_summary.tsv
│   ├── partitions
│   │   ├── cloud.txt
│   │   ├── exact_accessory.txt
│   │   ├── exact_core.txt
│   │   ├── persistent.txt
│   │   ├── S1.txt
│   │   ├── S2.txt
│   │   ├── S3.txt
│   │   ├── S4.txt
│   │   ├── S5.txt
│   │   ├── shell.txt
│   │   ├── soft_accessory.txt
│   │   └── soft_core.txt
│   ├── regions_of_genomic_plasticity.tsv
│   ├── rgp_families.tsv
│   ├── spots.tsv
│   └── summarize_spots.tsv
└── rgp_cluster
    ├── rgp_cluster.gexf
    ├── rgp_cluster.graphml
    └── rgp_cluster.tsv

7 directories, 30 files

---

# Data Analysis: Combining Pangenome and AMR Annotations

## Load Required Libraries

In [8]:
import pandas as pd
from pathlib import Path
import plotly.express as px

In [9]:
resistance_annotation_file = "amrfinder_result.tsv"
df_amrfinder = pd.read_csv(resistance_annotation_file, sep="\t")


df_amrfinder["amrfinder_annotation"] = True
df_amrfinder

,Protein id,Element symbol,Element name,Scope,Type,Subtype,Class,Subclass,Method,Target length,Reference sequence length,% Coverage of reference,% Identity to reference,Alignment length,Closest reference accession,Closest reference name,HMM accession,HMM description,amrfinder_annotation
0,AA98_RS0124760,qacEdelta1,quaternary ammonium compound efflux SMR transp...,core,STRESS,BIOCIDE,QUATERNARY AMMONIUM,QUATERNARY AMMONIUM,ALLELEP,116,115,100.0,100.00,115,WP_000679427.1,quaternary ammonium compound efflux SMR transp...,NF000276.2,quaternary ammonium compound efflux SMR transp...,True
1,AA98_RS0124915,aph(6)-Id,aminoglycoside O-phosphotransferase APH(6)-Id,core,AMR,AMR,AMINOGLYCOSIDE,STREPTOMYCIN,EXACTP,279,278,100.0,100.00,278,WP_000480972.1,aminoglycoside O-phosphotransferase APH(6)-Id,NF012171.0,APH(6)-I family aminoglycoside O-phosphotransf...,True
2,AA98_RS21625,blaTEM-1,broad-spectrum class A beta-lactamase TEM-1,core,AMR,AMR,BETA-LACTAM,BETA-LACTAM,ALLELEP,287,286,100.0,100.00,286,WP_000027057.1,broad-spectrum class A beta-lactamase TEM-1,NF000531.2,TEM family class A beta-lactamase,True
3,AA98_RS21640,aph(3'')-Ib,aminoglycoside O-phosphotransferase APH(3'')-Ib,core,AMR,AMR,AMINOGLYCOSIDE,STREPTOMYCIN,EXACTP,268,267,100.0,100.00,267,WP_001082319.1,aminoglycoside O-phosphotransferase APH(3'')-Ib,NF032895.1,aminoglycoside O-phosphotransferase APH(3'')-Ib,True
4,AA98_RS21645,sul2,sulfonamide-resistant dihydropteroate synthase...,core,AMR,AMR,SULFONAMIDE,SULFONAMIDE,EXACTP,272,271,100.0,100.00,271,WP_001043260.1,sulfonamide-resistant dihydropteroate synthase...,NF000295.1,sulfonamide-resistant dihydropteroate synthase...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,U0X53_RS20190,lnu(G),lincosamide nucleotidyltransferase Lnu(G),core,AMR,AMR,LINCOSAMIDE,LINCOSAMIDE,BLASTP,268,267,100.0,99.63,267,WP_002333496.1,lincosamide nucleotidyltransferase Lnu(G),NF033182.0,lincosamide nucleotidyltransferase Lnu(G),True
172,U0X53_RS25185,estT,macrolide hydrolase EstT,core,AMR,AMR,MACROLIDE,TYLOSIN,HMM,282,282,100.0,89.01,282,WP_185148407.1,macrolide hydrolase EstT,NF041759.1,macrolide hydrolase EstT,True
173,U0X53_RS25190,tet(X4),tetracycline-inactivating monooxygenase Tet(X4),core,AMR,AMR,TETRACYCLINE,TIGECYCLINE,EXACTP,386,385,100.0,100.00,385,WP_094309310.1,tetracycline-inactivating monooxygenase Tet(X4),NF033111.2,tetracycline-inactivating monooxygenase Tet(X),True
174,VSP21_RS23635,blaSHV-12,extended-spectrum class A beta-lactamase SHV-12,core,AMR,AMR,BETA-LACTAM,CEFIDEROCOL/CEPHALOSPORIN,ALLELEP,287,286,100.0,100.00,286,WP_002904004.1,extended-spectrum class A beta-lactamase SHV-12,NF000285.3,SHV family class A beta-lactamase,True
175,VSP37_RS23665,qnrD1,quinolone resistance pentapeptide repeat prote...,core,AMR,AMR,QUINOLONE,QUINOLONE,ALLELEP,215,214,100.0,100.00,214,WP_012634451.1,quinolone resistance pentapeptide repeat prote...,NF000139.2,QnrD family quinolone resistance pentapeptide ...,True

## Filter AMR Results

Keep only genes with AMR annotations (excluding virulence and stress response genes).

In [10]:


arm_filter = df_amrfinder['Type'] == "AMR" 
df_amr = df_amrfinder.loc[arm_filter][['Protein id', 'Element symbol', 'Element name', 'Scope', 'Type',
       'Subtype', 'Class', 'Subclass', 'Method',
       'HMM description', 'amrfinder_annotation']]


df_amr

,Protein id,Element symbol,Element name,Scope,Type,Subtype,Class,Subclass,Method,HMM description,amrfinder_annotation
1,AA98_RS0124915,aph(6)-Id,aminoglycoside O-phosphotransferase APH(6)-Id,core,AMR,AMR,AMINOGLYCOSIDE,STREPTOMYCIN,EXACTP,APH(6)-I family aminoglycoside O-phosphotransf...,True
2,AA98_RS21625,blaTEM-1,broad-spectrum class A beta-lactamase TEM-1,core,AMR,AMR,BETA-LACTAM,BETA-LACTAM,ALLELEP,TEM family class A beta-lactamase,True
3,AA98_RS21640,aph(3'')-Ib,aminoglycoside O-phosphotransferase APH(3'')-Ib,core,AMR,AMR,AMINOGLYCOSIDE,STREPTOMYCIN,EXACTP,aminoglycoside O-phosphotransferase APH(3'')-Ib,True
4,AA98_RS21645,sul2,sulfonamide-resistant dihydropteroate synthase...,core,AMR,AMR,SULFONAMIDE,SULFONAMIDE,EXACTP,sulfonamide-resistant dihydropteroate synthase...,True
6,AA98_RS22815,sul1,sulfonamide-resistant dihydropteroate synthase...,core,AMR,AMR,SULFONAMIDE,SULFONAMIDE,EXACTP,sulfonamide-resistant dihydropteroate synthase...,True
...,...,...,...,...,...,...,...,...,...,...,...
171,U0X53_RS20190,lnu(G),lincosamide nucleotidyltransferase Lnu(G),core,AMR,AMR,LINCOSAMIDE,LINCOSAMIDE,BLASTP,lincosamide nucleotidyltransferase Lnu(G),True
172,U0X53_RS25185,estT,macrolide hydrolase EstT,core,AMR,AMR,MACROLIDE,TYLOSIN,HMM,macrolide hydrolase EstT,True
173,U0X53_RS25190,tet(X4),tetracycline-inactivating monooxygenase Tet(X4),core,AMR,AMR,TETRACYCLINE,TIGECYCLINE,EXACTP,tetracycline-inactivating monooxygenase Tet(X),True
174,VSP21_RS23635,blaSHV-12,extended-spectrum class A beta-lactamase SHV-12,core,AMR,AMR,BETA-LACTAM,CEFIDEROCOL/CEPHALOSPORIN,ALLELEP,SHV family class A beta-lactamase,True
175,VSP37_RS23665,qnrD1,quinolone resistance pentapeptide repeat prote...,core,AMR,AMR,QUINOLONE,QUINOLONE,ALLELEP,QnrD family quinolone resistance pentapeptide ...,True

## Assign Pangenome Partitions to AMR Genes

Read partition files (Persistent, Shell, Cloud) and assign each AMR gene family to its partition.

In [11]:
def parse_partition_file(p_file):
    with open(p_file) as fl:
        return [l.strip() for l in fl]
        

shell_fams = parse_partition_file('ppanggolin_output/partitions/shell.txt')
cloud_fams = parse_partition_file('ppanggolin_output/partitions/cloud.txt')
persistent_fams = parse_partition_file('ppanggolin_output/partitions/persistent.txt')


df_amr.loc[df_amr['Protein id'].isin(persistent_fams), 'partition'] = "Persistent"
df_amr.loc[df_amr['Protein id'].isin(cloud_fams), 'partition'] = "Cloud"
df_amr.loc[df_amr['Protein id'].isin(shell_fams), 'partition'] = "Shell"

df_amr

,Protein id,Element symbol,Element name,Scope,Type,Subtype,Class,Subclass,Method,HMM description,amrfinder_annotation,partition
1,AA98_RS0124915,aph(6)-Id,aminoglycoside O-phosphotransferase APH(6)-Id,core,AMR,AMR,AMINOGLYCOSIDE,STREPTOMYCIN,EXACTP,APH(6)-I family aminoglycoside O-phosphotransf...,True,Shell
2,AA98_RS21625,blaTEM-1,broad-spectrum class A beta-lactamase TEM-1,core,AMR,AMR,BETA-LACTAM,BETA-LACTAM,ALLELEP,TEM family class A beta-lactamase,True,Shell
3,AA98_RS21640,aph(3'')-Ib,aminoglycoside O-phosphotransferase APH(3'')-Ib,core,AMR,AMR,AMINOGLYCOSIDE,STREPTOMYCIN,EXACTP,aminoglycoside O-phosphotransferase APH(3'')-Ib,True,Shell
4,AA98_RS21645,sul2,sulfonamide-resistant dihydropteroate synthase...,core,AMR,AMR,SULFONAMIDE,SULFONAMIDE,EXACTP,sulfonamide-resistant dihydropteroate synthase...,True,Shell
6,AA98_RS22815,sul1,sulfonamide-resistant dihydropteroate synthase...,core,AMR,AMR,SULFONAMIDE,SULFONAMIDE,EXACTP,sulfonamide-resistant dihydropteroate synthase...,True,Shell
...,...,...,...,...,...,...,...,...,...,...,...,...
171,U0X53_RS20190,lnu(G),lincosamide nucleotidyltransferase Lnu(G),core,AMR,AMR,LINCOSAMIDE,LINCOSAMIDE,BLASTP,lincosamide nucleotidyltransferase Lnu(G),True,Cloud
172,U0X53_RS25185,estT,macrolide hydrolase EstT,core,AMR,AMR,MACROLIDE,TYLOSIN,HMM,macrolide hydrolase EstT,True,Cloud
173,U0X53_RS25190,tet(X4),tetracycline-inactivating monooxygenase Tet(X4),core,AMR,AMR,TETRACYCLINE,TIGECYCLINE,EXACTP,tetracycline-inactivating monooxygenase Tet(X),True,Cloud
174,VSP21_RS23635,blaSHV-12,extended-spectrum class A beta-lactamase SHV-12,core,AMR,AMR,BETA-LACTAM,CEFIDEROCOL/CEPHALOSPORIN,ALLELEP,SHV family class A beta-lactamase,True,Cloud
175,VSP37_RS23665,qnrD1,quinolone resistance pentapeptide repeat prote...,core,AMR,AMR,QUINOLONE,QUINOLONE,ALLELEP,QnrD family quinolone resistance pentapeptide ...,True,Cloud

In [12]:
partition_to_color = {'Persistent': '#e59c04', 'Shell': '#00d860', 'Cloud': '#79deff'}
partition_order = ["Persistent", "Shell", "Cloud"]



df_amr_rgp_partition_total = df_amr.groupby(["partition"]).agg({
                                    "Protein id":"count"}).reset_index()

fig = px.bar(df_amr_rgp_partition_total, x='partition', y='Protein id', color="partition", 
             color_discrete_map=partition_to_color,
             category_orders={"partition": partition_order},
             title="Total AMR Gene Families per Partition",
             text='Protein id',
             labels={"Protein id": "# Gene Families<br>with AMR annotation", "partition": "Pangenome Partition"})

# Adjust text position to be outside the bars at the top
fig.update_traces(textfont_size=12, width=0.6)

fig.update_layout(
    autosize=False,
    width=700,
    height=450,
)
fig.show()

In [13]:

df_amr_rgp_partition = df_amr.groupby(["partition", "Class"]).agg({
                                    "Protein id":"count"}).reset_index()


fig = px.bar(df_amr_rgp_partition, x='Class', y='Protein id', color="partition", 
             color_discrete_map=partition_to_color,
             category_orders={"partition": partition_order},
             title="AMR Gene Families by Class and Partition",
             labels={"Protein id": "Number of Gene Families", "Class": "AMR Class"})
fig.show()

In [14]:
df_amr_persistent =df_amr.loc[df_amr['partition'] == "Persistent"][['Protein id', "partition", "Element symbol", "Element name", "Type", "Class"]]
df_amr_persistent

,Protein id,partition,Element symbol,Element name,Type,Class
73,EQS_RS0104745,Persistent,emrD,multidrug efflux MFS transporter EmrD,AMR,EFFLUX
94,ERJG_RS08325,Persistent,mdtM,multidrug efflux MFS transporter MdtM,AMR,EFFLUX
95,ERJG_RS09105,Persistent,blaEC,BlaEC family class C beta-lactamase,AMR,BETA-LACTAM
100,ERJG_RS12255,Persistent,acrF,multidrug efflux RND transporter permease subu...,AMR,EFFLUX

## Load RGP Clustering Results

Import the RGP cluster assignments generated in the previous step.

In [15]:
df_rgp_cluster = pd.read_csv('rgp_cluster/rgp_cluster.tsv', sep='\t')

df_rgp_cluster

                             RGPs       cluster  spot_id
0      NZ_JAYMMQ010000001.1_RGP_9  cluster_2326  spot_31
1      NZ_JAYMMO010000001.1_RGP_9  cluster_2326  spot_31
2     NZ_JAUGRN010000001.1_RGP_11  cluster_2326  spot_31
3      NZ_JAJLMA010000014.1_RGP_3  cluster_2326  spot_31
4      NZ_JANFFC010000001.1_RGP_7  cluster_2326  spot_31
...                           ...           ...      ...
8465   NZ_JALMOH010000152.1_RGP_0  cluster_2602  No spot
8466      NZ_JZDN01000080.1_RGP_0  cluster_2603  No spot
8467      NZ_LRKR01000111.1_RGP_0   cluster_573  No spot
8468   NZ_JBERAB010000098.1_RGP_0  cluster_2604  No spot
8469   NZ_JAXBSE010000015.1_RGP_0  cluster_2605  No spot

[8470 rows x 3 columns]

In [16]:
# read rgps families
rgp_families_file = Path('ppanggolin_output/rgp_families.tsv')
df_rgp_fams = pd.read_csv(rgp_families_file, sep='\t')
df_rgp_fams

                            rgp_id        family_id
0              NZ_GL872041.1_RGP_3     ERJG_RS19710
1              NZ_GL872041.1_RGP_3     ERJG_RS19705
2              NZ_GL872041.1_RGP_3  EC12741_RS17375
3              NZ_GL872041.1_RGP_3     ERJG_RS19695
4              NZ_GL872041.1_RGP_3     ERJG_RS19690
...                            ...              ...
119056  NZ_CAWNSZ010000182.1_RGP_1  EC12741_RS34080
119057  NZ_CAWNSZ010000182.1_RGP_1     ERJG_RS22035
119058  NZ_CAWNSZ010000182.1_RGP_1   ERJG_RS0124075
119059  NZ_CAWNSZ010000182.1_RGP_1     ERJG_RS22030
119060  NZ_CAWNSZ010000182.1_RGP_1     ERJG_RS22025

[119061 rows x 2 columns]

## Load Functional Modules

Import gene family module assignments to identify functional units in RGPs.

In [17]:
module_families_file = Path("ppanggolin_output/functional_modules.tsv")
df_module_fams = pd.read_csv(module_families_file, sep="\t")
df_module_fams

       module_id       family_id
0      module_53    ERJG_RS03010
1      module_53    ERJG_RS03005
2      module_53    ERJG_RS03000
3      module_53    ERJG_RS02995
4      module_53    ERJG_RS02990
...          ...             ...
3793  module_553  AABA30_RS18960
3794  module_553  AABA30_RS18970
3795  module_553  AABA30_RS18975
3796  module_553  AABA30_RS18980
3797  module_553  AABA30_RS18985

[3798 rows x 2 columns]

## Merge All Data Tables

Combine RGP families, cluster assignments, modules, and AMR annotations into a single dataframe for analysis.

In [18]:
df_rgp_info_merged = df_rgp_fams.merge(df_rgp_cluster, left_on="rgp_id", right_on="RGPs", how="left")
df_rgp_info_merged = df_rgp_info_merged.merge(df_module_fams, on="family_id", how="left")
df_rgp_info_merged = df_rgp_info_merged.merge(df_amr, left_on="family_id", right_on="Protein id", how="left")
df_rgp_info_merged

,rgp_id,family_id,RGPs,cluster,spot_id,module_id,Protein id,Element symbol,Element name,Scope,Type,Subtype,Class,Subclass,Method,HMM description,amrfinder_annotation,partition
0,NZ_GL872041.1_RGP_3,ERJG_RS19710,NZ_GL872041.1_RGP_3,cluster_1944,spot_0,module_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NZ_GL872041.1_RGP_3,ERJG_RS19705,NZ_GL872041.1_RGP_3,cluster_1944,spot_0,module_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NZ_GL872041.1_RGP_3,EC12741_RS17375,NZ_GL872041.1_RGP_3,cluster_1944,spot_0,module_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NZ_GL872041.1_RGP_3,ERJG_RS19695,NZ_GL872041.1_RGP_3,cluster_1944,spot_0,module_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NZ_GL872041.1_RGP_3,ERJG_RS19690,NZ_GL872041.1_RGP_3,cluster_1944,spot_0,module_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119056,NZ_CAWNSZ010000182.1_RGP_1,EC12741_RS34080,NZ_CAWNSZ010000182.1_RGP_1,cluster_719,spot_25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119057,NZ_CAWNSZ010000182.1_RGP_1,ERJG_RS22035,NZ_CAWNSZ010000182.1_RGP_1,cluster_719,spot_25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119058,NZ_CAWNSZ010000182.1_RGP_1,ERJG_RS0124075,NZ_CAWNSZ010000182.1_RGP_1,cluster_719,spot_25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119059,NZ_CAWNSZ010000182.1_RGP_1,ERJG_RS22030,NZ_CAWNSZ010000182.1_RGP_1,cluster_719,spot_25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119060,NZ_CAWNSZ010000182.1_RGP_1,ERJG_RS22025,NZ_CAWNSZ010000182.1_RGP_1,cluster_719,spot_25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

---

# Spot-Level Analysis

## Calculate Summary Statistics per Spot

Count RGPs, clusters, gene families, and modules for each genomic hotspot (spot).

In [19]:
# Create spot-level summary with some metrics
# Filter for rows with AMR annotation
has_amr = df_rgp_info_merged['amrfinder_annotation'].notna()


# Overall counts per spot
overall = df_rgp_info_merged.groupby('spot_id').agg(
    n_clusters=('cluster', 'nunique'),
    n_rgps=('RGPs', 'nunique'),
    n_families=('family_id', 'nunique'),
    n_modules=('module_id', 'nunique')
)

# AMR-specific counts per spot
amr_only = df_rgp_info_merged.loc[has_amr].groupby('spot_id').agg(
    n_clusters_with_amr=('cluster', 'nunique'),
    n_rgps_with_amr=('RGPs', 'nunique'),
    n_families_with_amr=('family_id', 'nunique'),
    n_modules_with_amr=('module_id', 'nunique')
)


# Combine into single dataframe
spot_summary = overall.join(amr_only, how='left').fillna(0).astype(int).reset_index()

spot_summary['prct_rgp_with_amr'] = (spot_summary['n_rgps_with_amr'] / spot_summary['n_rgps'] * 100).round(2)
spot_summary['prct_clusters_with_amr'] = (spot_summary['n_clusters_with_amr'] / spot_summary['n_clusters'] * 100).round(2)
spot_summary

,spot_id,n_clusters,n_rgps,n_families,n_modules,n_clusters_with_amr,n_rgps_with_amr,n_families_with_amr,n_modules_with_amr,prct_rgp_with_amr,prct_clusters_with_amr
0,No spot,2232,4214,9401,500,129,183,54,7,4.34,5.78
1,spot_0,1,17,15,2,0,0,0,0,0.00,0.00
2,spot_1,1,70,8,1,0,0,0,0,0.00,0.00
3,spot_10,5,13,117,6,0,0,0,0,0.00,0.00
4,spot_100,1,11,5,1,0,0,0,0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...
189,spot_95,4,6,74,4,0,0,0,0,0.00,0.00
190,spot_96,1,1,54,1,0,0,0,0,0.00,0.00
191,spot_97,1,1,11,1,0,0,0,0,0.00,0.00
192,spot_98,3,3,84,3,0,0,0,0,0.00,0.00
193,spot_99,1,1,43,0,0,0,0,0,0.00,0.00

In [20]:


# Scatter: spot size vs % RGPs with AMR, colored by number of AMR families
no_spot_filter = spot_summary["spot_id"] != "No spot"
 
fig = px.scatter(
    spot_summary.loc[no_spot_filter],
    x="n_rgps",
    y="prct_rgp_with_amr",
    hover_data=spot_summary.columns,
    color="n_families_with_amr",
    size="n_families_with_amr",
    title="Spot size vs % RGPs with AMR", # text="spot_of_interest",
    marginal_x="histogram", marginal_y="histogram"
)
fig.update_coloraxes(colorscale="Viridis")

fig.update_layout(
    autosize=False,
    width=1000,
    height=600,
    xaxis_title="Number of RGPs in spot",
    yaxis_title="% RGPs with AMR annotation",
    coloraxis_colorbar=dict(title="# AMR families")
)

# Add axis titles to marginal plots
fig.layout.xaxis2.title.text = "# Spot"

fig.layout.xaxis2.showticklabels = True 


fig.layout.yaxis3.title.text = "# Spot"

fig.layout.yaxis3.showticklabels = True 


fig.show()

---

# RGP Cluster Analysis

## Calculate Summary Statistics per RGP Cluster

Aggregate data by RGP cluster to identify clusters with AMR genes and their distribution across spots.

In [21]:
has_amr = df_rgp_info_merged['amrfinder_annotation'].notna()
no_spot_filter = df_rgp_info_merged['spot_id'] != "No spot"

# Overall counts per spot
overall = df_rgp_info_merged[no_spot_filter].groupby('cluster').agg(
    n_spots=('spot_id', 'nunique'),
    n_rgps=('RGPs', 'nunique'),
    n_families=('family_id', 'nunique'),
    n_modules=('module_id', 'nunique')
)

# AMR-specific counts per spot
amr_only = df_rgp_info_merged[no_spot_filter & has_amr ].groupby('cluster').agg(
    n_spots_with_amr=('spot_id', 'nunique'),
    n_rgps_with_amr=('RGPs', 'nunique'),
    n_families_with_amr=('family_id', 'nunique'),
    n_modules_with_amr=('module_id', 'nunique'),
)


# Combine into single dataframe
cluster_summary = overall.join(amr_only, how='left').fillna(0).reset_index()



cluster_summary['prct_rgp_with_amr'] = (cluster_summary['n_rgps_with_amr'] / cluster_summary['n_rgps'] * 100).round(2)
cluster_summary['prct_spot_with_amr'] = (cluster_summary['n_spots_with_amr'] / cluster_summary['n_spots'] * 100).round(2)


has_module = df_rgp_info_merged['module_id'].notna()
amr_modules = df_rgp_info_merged[has_module & has_amr].groupby('cluster').agg(
    amr_modules=('module_id', set),
)
amr_modules['amr_modules'] = amr_modules['amr_modules'].apply(lambda x: ' '.join(x) if isinstance(x, set) else x)


amr_spots = df_rgp_info_merged[has_amr & no_spot_filter].groupby('cluster').agg(
    amr_spots=('spot_id', set),
)
amr_spots['amr_spots'] = amr_spots['amr_spots'].apply(lambda x: ' '.join(x) if isinstance(x, set) else x)


cluster_summary = cluster_summary.merge(amr_modules, how='left', on='cluster').merge(amr_spots, how='left', on='cluster')
cluster_summary

,cluster,n_spots,n_rgps,n_families,n_modules,n_spots_with_amr,n_rgps_with_amr,n_families_with_amr,n_modules_with_amr,prct_rgp_with_amr,prct_spot_with_amr,amr_modules,amr_spots
0,cluster_0,1,36,5,1,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,cluster_1,1,82,5,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,cluster_10,1,10,8,1,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,cluster_1001,1,2,20,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,cluster_1008,1,1,2,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,cluster_957,1,2,7,1,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
506,cluster_966,1,2,4,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
507,cluster_984,1,3,13,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
508,cluster_988,1,1,62,6,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
509,cluster_998,1,7,86,9,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [22]:
spot_size_filter = cluster_summary['n_spots_with_amr'] > 0
fig = px.scatter(
    cluster_summary.loc[spot_size_filter].sort_values(by='n_spots_with_amr', ascending=False),
    x="cluster",
    y="n_spots_with_amr",
    hover_data=cluster_summary.columns,
    size="n_families_with_amr",
    color="n_families_with_amr",
)
fig.update_traces(marker=dict(line=dict(width=1, color='black')))
fig.show()